### ISSUE TITLE
bridge/under bridge roads displayed as crossing

### ISSUE THREAD

**Issue by matkoniecz** [tangrams/traditional-style#38]
expected: bridges are displayed in way that indicates that roads are not crossing

https://mapzen.com/tangram/play/?#18.50000/50.06934/19.94990
http://www.openstreetmap.org/#map=19/50.06904/19.94973

![selection_003](https://user-images.githubusercontent.com/899988/28260881-43d9e134-6add-11e7-85d6-6bf85980f2fd.png)

**Comment by matkoniecz** [comment]
I am not entirely sure is it possible using tangram (I tried and failed to achieve this effect).

**Comment by nvkelso** [comment]
This is controlled here:

https://github.com/tangrams/cinnabar-style/blob/gh-pages/cinnabar-style.yaml#L1701-L1708

```
        bridges-tunnels:
            filter: { any: [is_bridge: true, is_tunnel: true] }
            draw:
                lines:
                    #cap: butt
                    outline:
                        # except bridges and tunnels, their outlines should also self-sort
                        order: global.feature_order
```

If we always turned this on then the joins between road classes would incorrectly show casings at the junction (just go east of there a little bit).

It looks like the feature _is_ getting a correct `sort_rank` via Tilezen vector tiles, but it's a problem with the tile data in that `is_bridge` is missing. 

Looking closer this feature is `bridge=viaduct` in OSM: 

- https://www.openstreetmap.org/way/365016934

Back to Tilezen, we normalize bridge values to a generic boolean:

- https://github.com/tilezen/vector-datasource/blob/d3a072516d9b929937723efa2027c048ca61f20a/vectordatasource/transform.py#L230-L231

```
    if bridge in ('yes', 'true'):
        properties['is_bridge'] = True
```

Maybe we should be testing `if bridge not in ('no'):` instead?

Looking at TagInfo `bridge=viaduct` has over 51,000 uses:

- https://taginfo.openstreetmap.org/keys/bridge#values

Going back to why the `sort_rank` is correct, even though `is_bridge` is missing – because the feature has `layer=1` we give it `sort_rank` of 443 independent of the `bridge=*` OSM and transformed Tilezen value.

- https://github.com/tilezen/vector-datasource/blob/e324c7d3406895c065aa40bd5de5d66be491d720/queries.yaml#L220-L225
- https://github.com/tilezen/vector-datasource/blob/master/spreadsheets/sort_rank/roads.csv#L8
